apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ivolve-proj
  name: ivolve-proj
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ivolve-proj
  strategy: {}
  template:
    metadata:
      labels:
        app: ivolve-proj
    spec:
      containers:
      - image: 
        name: 
        resources: {}
status: {}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ivolve-app
  name: ivolve-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivolve-app
  strategy: {}
  template:
    metadata:
      labels:
        app: ivolve-app
    spec:
      containers:
      - image: 637423620989.dkr.ecr.us-east-1.amazonaws.com/ivolve-app:1
        name: ivolve-app
        resources: {}
status: {}
