apiVersion: v1
kind: Service
metadata:
  name: ivolve-proj-svc
  namespace: ivolve
spec:
  type: LoadBalancer
  selector:
    app: ivolve-proj
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP

